SELECT * FROM ENCARGOFERIASSAL13;


ALTER TABLE ENCARGOFERIASSAL13 ADD ENGAJAMENTO INT DEFAULT 0;
ALTER TABLE ENCARGOFERIASSAL13 ADD PUNICOES INT DEFAULT 0;
ALTER TABLE ENCARGOFERIASSAL13 ADD PUNICOESEPI INT DEFAULT 0;
ALTER TABLE ENCARGOFERIASSAL13 ADD PUNICOESDIASASO INT DEFAULT 0;
ALTER TABLE ENCARGOFERIASSAL13 ADD CAPACITACAO MONEY DEFAULT 0;
ALTER TABLE ENCARGOFERIASSAL13 ADD LISTAMULTIF INT DEFAULT 0;
ALTER TABLE ENCARGOFERIASSAL13 ADD FALTASTRABALHO INT DEFAULT 0;
ALTER TABLE ENCARGOFERIASSAL13 ADD HRTRABALHADAS INT DEFAULT 0;
ALTER TABLE ENCARGOFERIASSAL13 ADD ACIDENTESTRABALHO INT DEFAULT 0;
ALTER TABLE ENCARGOFERIASSAL13 ADD DIASAFASTADOINSS INT DEFAULT 0;
ALTER TABLE ENCARGOFERIASSAL13 ADD CURSOSEGTRABALHO INT DEFAULT 0;
ALTER TABLE ENCARGOFERIASSAL13 ADD QUESTIONARIO INT DEFAULT 0;