BEGIN

DECLARE @MES INT = 3;
DECLARE @ANO INT = 2015;

DECLARE @DTINICIO DATE = CONVERT(VARCHAR, @ANO) + '-' + CONVERT(VARCHAR, @MES) + '-1';
DECLARE @DTFIM DATE = DATEADD(DAY, -1, DATEADD(MONTH, 1, @DTINICIO));

SELECT 
T.MATRICULA,
T.NOME,
T.CATEGORIA,


(SELECT COUNT(*) FROM REQFUNCAO RQ INNER JOIN REQUISICAO R ON R.REQUISICAO = RQ.REQUISICAO 
	WHERE R.CANCELADO = 0 AND  RQ.VISUALIZAQUADRO = 1 AND (RQ.CALCULADO BETWEEN @DTINICIO AND @DTFIM) AND MATRICULA = T.MATRICULA) AS 'ENGAJAMENTO',

(SELECT COUNT(*) FROM OCORRENCIA O INNER JOIN GRUPO G ON O.GRUPO = G.GRUPO WHERE G.PUNICAO = 1  
AND (O.INICIO) >= @DTINICIO AND (O.TERMINO <= @DTFIM OR O.TERMINO IS NULL)
AND MATRICULA = T.MATRICULA)  AS 'PUNICOES',

(SELECT COUNT(*) FROM OCORRENCIA O INNER JOIN GRUPO G ON O.GRUPO = G.GRUPO WHERE G.EPI = 1  
AND (O.INICIO) >= @DTINICIO AND (O.TERMINO <= @DTFIM OR O.TERMINO IS NULL)
AND MATRICULA = T.MATRICULA)  AS 'PUNICOESEPI',

(SELECT ISNULL(SUM(DATEDIFF(DAY, O.INICIO, ISNULL(O.TERMINO, GETDATE()))),0) FROM OCORRENCIA O INNER JOIN GRUPO G ON O.GRUPO = G.GRUPO WHERE G.ASO = 1  
AND (O.INICIO) >= @DTINICIO AND (O.TERMINO <= @DTFIM OR O.TERMINO IS NULL)
AND MATRICULA = T.MATRICULA)  AS 'PUNICOESASO',

(SELECT (CONVERT(MONEY, 
(SELECT COUNT(*) FROM HABILITACAO WHERE (HABILITADO BETWEEN @DTINICIO AND @DTFIM) AND MATRICULA = T.MATRICULA AND (CHAMADA = 1 OR CHAMADA = 3))) 
* 100) / (SELECT COUNT(*) FROM FUNCAO F WHERE F.CATEGORIA = T.CATEGORIA))  AS 'CAPACITACAO',

(SELECT COUNT(*) FROM CAMBIOS C WHERE C. CHAMADA > 3 AND MATRICULA = T.MATRICULA) AS 'LISTAMULTI',

(SELECT COUNT(*) FROM OCORRENCIA O INNER JOIN REQFUNCAO RQ ON RQ.CFUNCAO = O.CFUNCAO 
WHERE (O.INICIO) >= @DTINICIO AND (O.TERMINO <= @DTFIM OR O.TERMINO IS NULL) AND O.GRUPO = 46 AND O.MATRICULA = T.MATRICULA) 'FALTAENGAJADO',

(SELECT COUNT(*)*6 FROM REQFUNCAO RQ WHERE (RQ.CALCULADO BETWEEN @DTINICIO AND @DTFIM) AND MATRICULA = T.MATRICULA) AS 'HORATRABALHADAS',

(SELECT COUNT(*) FROM OCORRENCIA O INNER JOIN REQFUNCAO RQ ON RQ.CFUNCAO = O.CFUNCAO 
WHERE (O.INICIO) >= @DTINICIO AND (O.TERMINO <= @DTFIM OR O.TERMINO IS NULL) AND O.GRUPO = 45 AND O.MATRICULA = T.MATRICULA) 'ACIDENTESTRABALHO',

(SELECT COUNT(*) FROM OCORRENCIA WHERE GRUPO = 6 AND MATRICULA = T.MATRICULA AND (INICIO) >= @DTINICIO AND (TERMINO <= @DTFIM OR TERMINO IS NULL)) AS 'AFASTAMENTOINSS',

(SELECT (CASE WHEN 
			(SELECT COUNT(*) FROM CURSO_TURMA CT INNER JOIN CURSO C ON C.CURSO = CT.CURSO AND C.TIPOCURSO = 1 WHERE CT.INICIO >= @DTINICIO) = 0  
		THEN 
			100 
		ELSE 
			(CONVERT(MONEY, (SELECT COUNT(*) FROM CURSO_TURMA_ALUNOS CTA WHERE CTA.CURSO_TURMA IN (SELECT CT.CURSO_TURMA FROM CURSO_TURMA CT INNER JOIN CURSO C ON C.CURSO = CT.CURSO AND C.TIPOCURSO = 1
WHERE CT.INICIO >= @DTINICIO) AND CTA.MATRICULA = T.MATRICULA))*100 / (SELECT COUNT(*) FROM CURSO_TURMA CT INNER JOIN CURSO C ON C.CURSO = CT.CURSO AND C.TIPOCURSO = 1
WHERE CT.INICIO >= @DTINICIO)) END)) AS 'CURSOSSEGTRABALHO',

'?' AS 'QUESTIONARIO'



FROM TRABALHADOR T
WHERE T.EFETIVO = 1 AND T.EXCLUIDO = 0

END;