BEGIN
	DECLARE @MATRICULA INT, @PAREDE INT, @SITUACAO INT, @DIA DATE;
	
	DECLARE C_TRABALHADOR CURSOR FOR
		SELECT T.MATRICULA, F.PAREDE, F.SITUACAO, F.DIA
		FROM TRABALHADOR T
			LEFT JOIN FREQUENCIA F ON F.MATRICULA = T.MATRICULA
		WHERE 
			T.EFETIVO = 1
			AND T.EXCLUIDO = 0;
	
	OPEN C_TRABALHADOR;
	FETCH NEXT FROM C_TRABALHADOR INTO @MATRICULA, @PAREDE, @SITUACAO, @DIA;
	DELETE FROM ASSIDUIDADE
	
	WHILE @@FETCH_STATUS = 0
	BEGIN
		DECLARE @TEM_OCORRENCIA VARCHAR(MAX);
		SET @TEM_OCORRENCIA = (SELECT TOP 1 DESCRICAO FROM OCORRENCIA O 
			WHERE O.MATRICULA = @MATRICULA
				AND @DIA BETWEEN O.INICIO AND O.TERMINO);
				
		IF @TEM_OCORRENCIA <> '' --Existe alguma ocorrência
		BEGIN
			INSERT INTO ASSIDUIDADE(MATRICULA, PAREDE, DATA, SITUACAO, OBSERVACAO, PORCENTAGEM, VAGAS)
				VALUES(@MATRICULA, @PAREDE, @DIA, 0, @TEM_OCORRENCIA, 0, 0);
		END
		ELSE
		BEGIN
			DECLARE @ERA_BOCA INT;
			SET @ERA_BOCA = (SELECT COUNT(*) FROM AGULHADO A 
				WHERE 
					A.MATRICULA = @MATRICULA 
					AND A.PAREDE = @PAREDE
					AND A.DATA = @DIA);
					
			DECLARE @VAGAS INT;
			
			SET @VAGAS = (SELECT TOP 1
				(SELECT COUNT(*) FROM REQFUNCAO RF1 WHERE RF1.FUNCAO = RF.FUNCAO AND RF1.REQUISICAO = R.REQUISICAO) AS VAGAS 
				FROM REQFUNCAO RF 
				INNER JOIN REQUISICAO R ON RF.REQUISICAO = R.REQUISICAO
				WHERE RF.MATRICULA = @MATRICULA 
				AND R.PAREDE = @PAREDE
				AND R.DIA = @DIA);
			
			DECLARE @REQUISICAO INT;
			SET @REQUISICAO = (SELECT R.REQUISICAO FROM REQUISICAO R INNER JOIN REQFUNCAO RF ON R.REQUISICAO = RF.REQUISICAO 
				WHERE RF.MATRICULA = @MATRICULA 
				AND R.PAREDE = @PAREDE
				AND R.DIA = @DIA);
					
			IF @ERA_BOCA > 0 AND @VAGAS IS NULL --Se o funcionário é o da vez E NAO PREENCHOU NENHUMA VAGA
			BEGIN
				INSERT INTO ASSIDUIDADE(MATRICULA, PAREDE, DATA, SITUACAO, OBSERVACAO, REQUISICAO, PORCENTAGEM, VAGAS)
					VALUES(@MATRICULA, @PAREDE, @DIA, 0, 'Era Boca, mas não preenchou nenhuma vaga.', @REQUISICAO, 0, @VAGAS);
			END
			ELSE IF @ERA_BOCA > 0 AND @VAGAS > 0  --Se o funcionário é o da vez E PREENCHOU AS VAGAS
			BEGIN
				INSERT INTO ASSIDUIDADE(MATRICULA, PAREDE, DATA, SITUACAO, OBSERVACAO, REQUISICAO, PORCENTAGEM, VAGAS)
					VALUES(@MATRICULA, @PAREDE, @DIA, 1, 'Era Boca, E preenchou nenhuma vaga', @REQUISICAO, 0, @VAGAS);
			END
			ELSE IF @VAGAS > 0 
			BEGIN
				INSERT INTO ASSIDUIDADE(MATRICULA, PAREDE, DATA, SITUACAO, OBSERVACAO, REQUISICAO, PORCENTAGEM, VAGAS)
					VALUES(@MATRICULA, @PAREDE, @DIA, 1, '', @REQUISICAO, 0, @VAGAS);
			END
			ELSE
			BEGIN
				INSERT INTO ASSIDUIDADE(MATRICULA, PAREDE, DATA, SITUACAO, OBSERVACAO, REQUISICAO, PORCENTAGEM, VAGAS)
					VALUES(@MATRICULA, @PAREDE, @DIA, 0, '', @REQUISICAO, 0, @VAGAS);
			END
		END
		
		FETCH NEXT FROM C_TRABALHADOR INTO @MATRICULA, @PAREDE, @SITUACAO, @DIA;
	END 
	CLOSE C_TRABALHADOR;
	DEALLOCATE C_TRABALHADOR;

END;