--DROP PROCEDURE SP_CRIAR_ASSIDUIDADE;

ALTER PROCEDURE SP_CRIAR_ASSIDUIDADE @P_DATA DATE , @P_DATAFIM DATE
AS

BEGIN
	/*
	Regras :
	Verificar se possui ocorrência, senao NULL; OK
	Verificar se tem as 11h da ultima parede, senao NULL; OK
	Verificar se está agulhado, senao NULL;
	Verificar frequencia, senao 0; OK
	Verificar se está engajado, se sim 1. OK
	*/
	SET DATEFORMAT dmy;
		
	DECLARE @JA_INSERIU INT,  @TEM_ASSIDUIDADE INT,  @MATRICULA INT, @P_PAREDE INT, @REQUISICAO INT, @FUNCAO INT, @DIA DATE;
	
	SET @TEM_ASSIDUIDADE = 0;
	
	DECLARE C_TRABALHADOR CURSOR FOR
		SELECT T.MATRICULA FROM TRABALHADOR T 
			WHERE	T.EFETIVO = 1
					AND T.EXCLUIDO = 0;
	
	DECLARE @DATAAUX DATE = @P_DATA;
	
	IF @P_DATA <= @P_DATAFIM 
	BEGIN
		OPEN C_TRABALHADOR;
		FETCH NEXT FROM C_TRABALHADOR INTO @MATRICULA;
	
		WHILE @@FETCH_STATUS = 0
		BEGIN	
			/*
			SET @P_DATA = '01/'+CAST(@P_MES AS varchar)+'/'+CAST(@P_ANO AS varchar)
			SET @P_DATAFIM = '01/'+CAST(@P_MES+1 AS varchar)+'/'+CAST(@P_ANO AS varchar)
			SET @P_DATAFIM = DATEADD(DAY, -1, @P_DATAFIM)
			*/
			
			PRINT '===========================================';
			PRINT @MATRICULA;			
			
			WHILE @P_DATA <= @P_DATAFIM
			BEGIN

				DECLARE @TEM_OCORRENCIA VARCHAR(MAX);
				SET @TEM_OCORRENCIA = (SELECT TOP 1 DESCRICAO FROM OCORRENCIA O 
					WHERE O.MATRICULA = @MATRICULA
						AND @P_DATA BETWEEN O.INICIO AND O.TERMINO);
				
				SET @P_PAREDE = 1;
				
				IF @TEM_OCORRENCIA <> '' --Caso exista ocorrência ja insere uma 
				BEGIN
					INSERT INTO ASSIDUIDADE(MATRICULA, PAREDE, DATA, SITUACAO, REQUISICAO, OBSERVACAO)
						VALUES(@MATRICULA, NULL, @P_DATA, NULL, NULL, @TEM_OCORRENCIA);
				END
				ELSE
				BEGIN
					DECLARE @TEM_FREQUENCIA INT; --Se existe frequência
					DECLARE @INTERVALO INT; --Qual o intervalo
						
					DECLARE @SITUACAO_FREQ INT; --Situação da frequencia
					SET @SITUACAO_FREQ = (SELECT TOP 1 SITUACAO FROM FREQUENCIA F 
						WHERE F.MATRICULA = @MATRICULA
							AND F.DIA = @P_DATA);
								
					SET @JA_INSERIU = 0;

					WHILE @P_PAREDE <= 4
					BEGIN						
						PRINT @P_PAREDE;
						
						DECLARE @ERA_AGULHADO INT;
						DECLARE @CONT_REQFUNCAO INT;
						DECLARE @
						
						SET @TEM_FREQUENCIA = (SELECT COUNT(*) FROM FREQUENCIA F 
							WHERE F.MATRICULA = @MATRICULA
								AND F.DIA = @P_DATA AND F.PAREDE = @P_PAREDE);
						
						SET @INTERVALO = (SELECT TOP 1 INTERVALO FROM FREQUENCIA F 
							WHERE F.MATRICULA = @MATRICULA
								AND F.DIA = @P_DATA AND F.PAREDE = @P_PAREDE);						
						 
						SET @CONT_REQFUNCAO = (SELECT COUNT(RF.FUNCAO) FROM REQFUNCAO RF 
								INNER JOIN REQUISICAO R ON R.REQUISICAO = RF.REQUISICAO
								WHERE RF.MATRICULA = @MATRICULA AND R.PAREDE = @P_PAREDE);
											
						SET @ERA_AGULHADO = (SELECT COUNT(*) FROM AGULHADO A 
							WHERE 
								A.MATRICULA = @MATRICULA 
								AND A.PAREDE = @P_PAREDE
								AND A.DATA = @DIA);
										
						SET @TEM_ASSIDUIDADE = (SELECT COUNT(*) FROM ASSIDUIDADE 
							WHERE MATRICULA = @MATRICULA AND PAREDE = @P_PAREDE AND DATA = @P_DATA)
						
						SET @REQUISICAO = (SELECT R.REQUISICAO FROM REQUISICAO R INNER JOIN REQFUNCAO RF ON R.REQUISICAO = RF.REQUISICAO 
							WHERE RF.MATRICULA = @MATRICULA 
							AND R.PAREDE = @P_PAREDE
							AND R.DIA = @P_DATA);
						
						
						
						IF @TEM_ASSIDUIDADE = 0 
						BEGIN
							IF @TEM_FREQUENCIA = 0 --AND @JA_INSERIU = 0
							BEGIN
								PRINT 'NÃO TEM FREQUENCIA'							
								--INSERT INTO ASSIDUIDADE(MATRICULA, PAREDE, DATA, SITUACAO, REQUISICAO, OBSERVACAO) VALUES(@MATRICULA, @P_PAREDE, @P_DATA, 0, 0, 'Sem frequência');			
								--SET @JA_INSERIU = 1;				
							END
							ELSE IF @INTERVALO > 1 --AND @JA_INSERIU = 0
							BEGIN
								PRINT 'INTERVALO MAOIR'
								--INSERT INTO ASSIDUIDADE(MATRICULA, PAREDE, DATA, SITUACAO, REQUISICAO, OBSERVACAO) VALUES(@MATRICULA, @P_PAREDE, @P_DATA, null, 0, 'TPA com menos de 11h');
								--SET @JA_INSERIU = 1;
							END 
							ELSE IF @SITUACAO_FREQ = 2 --AND @CONT_REQFUNCAO > 1 AND @JA_INSERIU = 0
							BEGIN
								PRINT 'SITUACAO DE FREQUENCIA 2'
								--INSERT INTO ASSIDUIDADE(MATRICULA, PAREDE, DATA, SITUACAO, REQUISICAO, OBSERVACAO) VALUES(@MATRICULA, @P_PAREDE, @P_DATA, 0, NULL, 'TPA embarcado foi engajado eu outra requisição');
								--SET @JA_INSERIU = 1;
							END
							ELSE --IF @JA_INSERIU = 0
							BEGIN	
								PRINT 'JOINHA !!!!'
								--INSERT INTO ASSIDUIDADE(MATRICULA, PAREDE, DATA, SITUACAO, REQUISICAO, OBSERVACAO) VALUES(@MATRICULA, @P_PAREDE, @P_DATA, 1, @REQUISICAO, '');
								--SET @JA_INSERIU = 1;
							END;
						END;
						
						SET @P_PAREDE = @P_PAREDE + 1; 
					END;
					SET @JA_INSERIU = 0;
				END;
												
				SET @P_DATA = DATEADD(DAY, 1, @P_DATA);
			END;
			
			SET @P_DATA = @DATAAUX;
			
			FETCH NEXT FROM C_TRABALHADOR INTO @MATRICULA;
		END;
	END;
	CLOSE C_TRABALHADOR;
	DEALLOCATE C_TRABALHADOR;



	--IF (@@TRANCOUNT > 0) Begin
    --Insert Into [LOG] (auto, login, tabela, campo, descricao) Values ((select MAX(auto)+1 From log), 'ASSIDUIDADE', 'SP', 'Executada', 'SP Executada com Sucesso');
	--	COMMIT TRANSACTION;
	--END
END