--DROP PROCEDURE SP_CRIAR_ASSIDUIDADE 
--USE ogmocedesenv
CREATE PROCEDURE SP_CRIAR_ASSIDUIDADE @P_DATA DATE , @P_DATAFIM DATE
AS

BEGIN
	DECLARE @P_PAREDE INT;
	DECLARE @P_VAGAS INT;
	DECLARE @P_CAMBIO INT;
	DECLARE @P_NUMERO INT;
	DECLARE @P_AGULHADA INT;
	DECLARE @MATRICULA INT;
	
	DECLARE C_TRABALHADOR CURSOR FOR
		SELECT  T.MATRICULA FROM TRABALHADOR T 
			WHERE	T.EFETIVO = 1
					AND T.EXCLUIDO = 0;
	
	DECLARE @DATAAUX DATE = @P_DATA;
	
	IF @P_DATA <= @P_DATAFIM 
	BEGIN
		OPEN C_TRABALHADOR;
		FETCH NEXT FROM C_TRABALHADOR INTO @MATRICULA;
	
		WHILE @@FETCH_STATUS = 0
		BEGIN	
			PRINT @MATRICULA;
			WHILE @P_DATA <= @P_DATAFIM
			BEGIN
				SET @P_PAREDE = 1;
				WHILE @P_PAREDE <= 4
				BEGIN
					PRINT @P_PAREDE;
					DECLARE C_CAMBIOS CURSOR FOR
						SELECT F.CAMBIO, COUNT(*)
						FROM REQUISICAO R
						JOIN REQFUNCAO RF ON RF.REQUISICAO = R.REQUISICAO
						JOIN FUNCAO F ON F.FUNCAO = RF.FUNCAO
						WHERE R.DIA = @P_DATA 
						  AND R.PERIODO = @P_PAREDE
						  AND R.CANCELADO =0
						  AND RF.VISUALIZAQUADRO = 1
						  AND F.CATEGORIA IN (24,28,43)
						GROUP BY F.CAMBIO;
						
						OPEN C_CAMBIOS;
						FETCH NEXT FROM C_CAMBIOS INTO @P_CAMBIO, @P_VAGAS;
						
						DECLARE @P_COUNT_CAMBIOS INT = 0;
						DECLARE @P_COUNT_SEMAGULHADA INT = 0;
						DECLARE @P_COUNT_TEMREQ INT = 0;
						DECLARE @P_COUNT_NAOTEMREQ INT = 0;
						DECLARE @P_COUNT_NAOFEZ11H INT = 0;
						DECLARE @P_COUNT_TEMOCORRENCIA INT = 0;
						
						WHILE @@FETCH_STATUS = 0
						BEGIN
							SET @P_COUNT_CAMBIOS = @P_COUNT_CAMBIOS + 1;
							SET @P_NUMERO = (SELECT NUMERO FROM AGULHADO WHERE DATA = @P_DATA AND PAREDE = @P_PAREDE AND CAMBIO = @P_CAMBIO AND CHAMADA = 1);
							SET @P_AGULHADA = (SELECT COUNT(*) FROM 
								(SELECT  ROW_NUMBER() OVER (ORDER BY NUMERO) AS VAGA, MATRICULA, NUMERO FROM CAMBIOS 
									WHERE CAMBIO = @P_CAMBIO AND CHAMADA = 1 AND NUMERO >= @P_NUMERO ) AS TABELA WHERE VAGA BETWEEN 1 AND @P_VAGAS AND MATRICULA = @MATRICULA);
							
							DECLARE @P_FEZ11H INT;
							DECLARE @P_PERIODOANT1 INT;
							DECLARE @P_PERIODOANT2 INT;
							DECLARE @P_DATAANT DATE = DATEADD(DAY, -1, @P_DATA);
							
							SET @P_PERIODOANT1 = @P_PAREDE - 1;
							SET @P_PERIODOANT2 = @P_PAREDE - 2;
							
							IF @P_PERIODOANT1 <= 0 BEGIN
								SET @P_PERIODOANT1 = @P_PERIODOANT1 + 4;
							END;
							
							IF @P_PERIODOANT2 <= 0 BEGIN
								SET @P_PERIODOANT2 = @P_PERIODOANT2 + 4;
							END
							
							SET @P_FEZ11H = (SELECT COUNT(*)
								FROM REQUISICAO R
								JOIN REQFUNCAO RF ON RF.REQUISICAO = R.REQUISICAO
								WHERE ((R.DIA = @P_DATAANT AND R.PERIODO = @P_PERIODOANT1) OR (R.DIA = @P_DATAANT AND R.PERIODO = @P_PERIODOANT2))
								  AND R.CANCELADO = 0
								  AND RF.VISUALIZAQUADRO = 1
								  AND RF.MATRICULA = @MATRICULA);
							
							DECLARE @P_OCORRENCIA_DCR VARCHAR(MAX);
							SET @P_OCORRENCIA_DCR = (SELECT O.DESCRICAO FROM OCORRENCIA O 
								WHERE O.MATRICULA = @MATRICULA 
								AND ((@P_DATA BETWEEN O.INICIO AND O.TERMINO )
								 OR (@P_DATA >= O.INICIO AND O.TERMINO IS NULL))
								AND O.TRAVATPA = 1);
							
							DECLARE @P_REQUISICAO INT;
							SET @P_REQUISICAO = (SELECT COUNT(*)
								FROM REQUISICAO R
								JOIN REQFUNCAO RF ON RF.REQUISICAO = R.REQUISICAO
								WHERE (R.DIA = @P_DATA AND R.PERIODO = @P_PAREDE)
								  AND R.CANCELADO = 0
								  AND RF.VISUALIZAQUADRO = 1
								  AND RF.MATRICULA = @MATRICULA);
							
							IF @P_AGULHADA = 0 
							BEGIN
								SET @P_COUNT_SEMAGULHADA = @P_COUNT_SEMAGULHADA + 1;
							END	
							ELSE
							BEGIN
								IF @P_FEZ11H > 0
								BEGIN
									SET @P_COUNT_NAOFEZ11H =  @P_COUNT_NAOFEZ11H + 1;
								END
								ELSE
								BEGIN
									IF @P_OCORRENCIA_DCR <> ''  
									BEGIN 
										SET @P_COUNT_TEMOCORRENCIA = @P_COUNT_TEMOCORRENCIA + 1;
									END
									ELSE
									BEGIN
										IF @P_REQUISICAO = 0
										BEGIN
											SET @P_COUNT_NAOTEMREQ =  @P_COUNT_NAOTEMREQ + 1;
										END
										ELSE
										BEGIN
											SET @P_COUNT_TEMREQ =  @P_COUNT_TEMREQ + 1
										END;
									END;
								END;
								
							END;
							FETCH NEXT FROM C_CAMBIOS INTO @P_CAMBIO, @P_VAGAS;	
						END;
						CLOSE C_CAMBIOS;
						DEALLOCATE C_CAMBIOS;
						
						
						IF @P_COUNT_TEMOCORRENCIA > 0
							INSERT INTO ASSIDUIDADE(MATRICULA, PAREDE, DATA, SITUACAO, REQUISICAO, OBSERVACAO) VALUES(@MATRICULA, @P_PAREDE, @P_DATA, 1, NULL, 'TEM OCORRÊNCIA : ' + @P_OCORRENCIA_DCR);
						ELSE IF @P_COUNT_NAOFEZ11H > 0
							INSERT INTO ASSIDUIDADE(MATRICULA, PAREDE, DATA, SITUACAO, REQUISICAO, OBSERVACAO) VALUES(@MATRICULA, @P_PAREDE, @P_DATA, 0, NULL, 'NÃO FEZ 11H');
						ELSE IF @P_COUNT_TEMREQ > 0
							INSERT INTO ASSIDUIDADE(MATRICULA, PAREDE, DATA, SITUACAO, REQUISICAO, OBSERVACAO) VALUES(@MATRICULA, @P_PAREDE, @P_DATA, 1, NULL, 'OK');
						ELSE IF @P_COUNT_SEMAGULHADA > 0
							INSERT INTO ASSIDUIDADE(MATRICULA, PAREDE, DATA, SITUACAO, REQUISICAO, OBSERVACAO) VALUES(@MATRICULA, @P_PAREDE, @P_DATA, NULL, NULL, 'NÃO ERA A VEZ NA RODA');
						ELSE
							INSERT INTO ASSIDUIDADE(MATRICULA, PAREDE, DATA, SITUACAO, REQUISICAO, OBSERVACAO) VALUES(@MATRICULA, @P_PAREDE, @P_DATA, 0, NULL, '');
						
					SET @P_PAREDE = @P_PAREDE + 1; 
				END;
				SET @P_PAREDE = 1; 
				SET @P_DATA = DATEADD(DAY, 1, @P_DATA);
			END;
			SET @P_DATA = @DATAAUX;			
			FETCH NEXT FROM C_TRABALHADOR INTO @MATRICULA;
		END;
		CLOSE C_TRABALHADOR;
		DEALLOCATE C_TRABALHADOR;
	END;
END;